# Generated by Django 2.1.7 on 2019-03-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonegymain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease2',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=50)),
                ('logFC', models.FloatField(blank=True, default=None, null=True)),
                ('AveExpr', models.FloatField(blank=True, default=None, null=True)),
                ('t', models.FloatField(blank=True, default=None, null=True)),
                ('P_Value', models.FloatField(blank=True, default=None, null=True)),
                ('adj_P_Val', models.FloatField(blank=True, default=None, null=True)),
                ('B', models.FloatField(blank=True, default=None, null=True)),
                ('dataset', models.CharField(max_length=50)),
                ('category', models.IntegerField()),
            ],
        ),
    ]
